name: CI/CD Pipeline for Azure Deployment

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: windows-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.302'

      - name: Restore dependencies
        run: dotnet restore PizzaStore.csproj

      - name: Build the application
        run: dotnet build PizzaStore.csproj --configuration Release

      - name: Publish the application
        run: dotnet publish PizzaStore.csproj -c Release -o ./publish

      - name: Deploy to Azure Web App using Publish Profile
        uses: azure/webapps-deploy@v2
        with:
          app-name: "PizzaStore-WebApp"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
